-d G:\Other computers\My Computer\study_folder_sh\design cpu\top_cpu\impl\gwsynthesis\top_cpu.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst G:\Other computers\My Computer\study_folder_sh\design cpu\top_cpu\src\top_cpu.cst
-cfg G:\Other computers\My Computer\study_folder_sh\design cpu\top_cpu\impl\pnr\device.cfg
-sdc G:\Other computers\My Computer\study_folder_sh\design cpu\top_cpu\src\top_cpu.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
